name: intl_phone_field2
description: A customised Flutter TextFormField to input international phone number along with country code.
version: 3.3.3
homepage: https://github.com/nirmalyohannan/intl_phone_field2

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  test: ^1.17.12

flutter:
  assets:
    - assets/flags/
